export const ANIME_QUOTES = [
    { text: "Whatever you lose, you'll find it again. But what you throw away you'll never get back.", author: "Kenshin Himura" },
    { text: "Fear is not evil. It tells you what your weakness is. And once you know your weakness, you can become stronger as well as kinder.", author: "Gildarts Clive" },
    { text: "Knowing what it feels like to be in pain, is exactly why we try to be kind to others.", author: "Jiraiya" },
    { text: "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be.", author: "Naruto Uzumaki" },
    { text: "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful.", author: "Roy Mustang" },
    { text: "A person grows up when he's able to overcome hardships. Protection is important, but there are some things that a person must learn on his own.", author: "Jiraiya" },
    { text: "Hard work is worthless for those that don't believe in themselves.", author: "Naruto Uzumaki" },
    { text: "If you can't find a reason to fight, then you shouldn't be fighting.", author: "Akame" },
    { text: "The moment you think of surrender, think of the reason why you held on so long.", author: "Natsu Dragneel" },
    { text: "Power is not will, it is the phenomenon of physically making things happen.", author: "Madara Uchiha" },
    { text: "It's more important to master the cards you're holding than to complain about the ones your opponent was dealt.", author: "Grimsley" },
    { text: "Push through the pain, giving up hurts more.", author: "Vegeta" },
    { text: "Even if I die, you keep living okay? Live to see the end of this world, and to see why it was born.", author: "Akihiko Kayaba" },
    { text: "I'll leave tomorrow's problems to tomorrow's me.", author: "Saitama" },
    { text: "In our world, the strong eat the weak. The strong live and the weak die.", author: "Makoto Shishio" },
    { text: "If you don't take risks, you can't create a future.", author: "Monkey D. Luffy" },
    { text: "A dropout will beat a genius through hard work.", author: "Rock Lee" },
    { text: "I'll take a potato chip... and EAT IT!", author: "Light Yagami" },
    { text: "Human strength is to have the power to change oneself.", author: "Saitama" },
    { text: "Forgetting is like a wound. The wound may heal, but it has already left a scar.", author: "Monkey D. Luffy" },
    { text: "The only thing we're allowed to do... is to believe that we won't regret the choice we made.", author: "Levi Ackerman" },
    { text: "If you don't share someone's pain, you can never understand them.", author: "Nagato" },
    { text: "Whether a fish lives in a clear stream or a ditch, so long as it continues swimming forward, it will grow up beautifully.", author: "Koro-sensei" },
    { text: "It’s not the face that makes someone a monster, it’s the choices they make with their lives.", author: "Naruto Uzumaki" },
    { text: "Vision is not what your eyes see, but an image that your brain comprehends.", author: "Touko Aozaki" },
    { text: "A place where someone still thinks of you is a place you can call home.", author: "Jiraiya" },
    { text: "Thinking you're no good and worthless is the worst thing you can do.", author: "Nobita" },
    { text: "If you can’t do something, then don’t. Focus on what you can do.", author: "Shiroe" },
    { text: "People’s lives don’t end when they die. It ends when they lose faith.", author: "Itachi Uchiha" },
    { text: "The ticket to the future is always open.", author: "Vash the Stampede" }
];
